name: Laravel

on: push

env:
  SSH_HOST: 188.225.47.78
  SSH_PORT: 22
  SSH_USER: root
  SSH_KEY: ${{ secrets.MY_TIMEWEB }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm i && npm run build

    - name: SSH remote delete dir
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SSH_HOST }}
        port: ${{ env.SSH_PORT }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        script: |
          cd /var/www/ilya/data/www/
          rm -rf /var/www/ilya/data/www/shop.ivelini.ru

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.SSH_HOST }}
        port: ${{ env.SSH_PORT }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        source: ./*, !.gitignore, !.github, !.git, !.gitattributes, !./docker, !.docker-compose.yml, !.package-lock.json, !.composer.lock
        target: /var/www/ilya/data/www/shop.ivelini.ru

    - name: SSH run remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SSH_HOST }}
        port: ${{ env.SSH_PORT }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        script: |
          cp /var/www/ilya/data/www/build/.env.backend /var/www/ilya/data/www/shop.ivelini.ru/.env
          cp /var/www/ilya/data/www/build/composer.phar /var/www/ilya/data/www/shop.ivelini.ru/composer.phar
          cd /var/www/ilya/data/www/shop.ivelini.ru
          /opt/php82/bin/php ./composer.phar install
          /opt/php82/bin/php artisan storage:link
          /opt/php82/bin/php artisan migrate --force
          /opt/php82/bin/php /var/www/ilya/data/www/shop.ivelini.ru/composer.phar dump-autoload
          /opt/php82/bin/php artisan optimize
          chown -R ilya:ilya ../shop.ivelini.ru
