name: Laravel

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm i && npm run build

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: 188.225.47.78
        port: 22
        username: root
        key: ${{ secrets.MY_TIMEWEB }}
        source: ./*, !.gitignore, !.github, !.git, !.gitattributes, !./docker, !.docker-compose.yml
        target: /var/www/ilya/data/www/shop.ivelini.ru

    - name: SSH run remote command
      uses: appleboy/ssh-action@master
      with:
        host: 188.225.47.78
        port: 22
        username: root
        key: ${{ secrets.MY_TIMEWEB }}
        script: |
          cp /var/www/ilya/data/www/build/.env.backend /var/www/ilya/data/www/shop.ivelini.ru/.env
          cp /var/www/ilya/data/www/build/composer.phar /var/www/ilya/data/www/shop.ivelini.ru/composer.phar
          cd /var/www/ilya/data/www/shop.ivelini.ru
          /opt/php82/bin/php /var/www/ilya/data/www/shop.ivelini.ru/composer.phar install
          /opt/php82/bin/php artisan migrate --force
          /opt/php82/bin/php /var/www/ilya/data/www/shop.ivelini.ru/composer.phar dump-autoload
          /opt/php82/bin/php artisan optimize
          npm install
          npm run build
          chown -R ilya:ilya ../shop.ivelini.ru
