name: Laravel

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: 188.225.47.78
        port: 22
        username: root
        key: ${{ secrets.MY_TIMEWEB }}
        source: ./
        target: /var/www/ilya/data/www/shop.ivelini.ru
