name: Laravel

on: push

env:
  SSH_HOST: 109.71.242.118
  SSH_PORT: 22
  SSH_USER: root
  SSH_KEY: ${{ secrets.TIMEWEB2 }}
  WORKDIR: /var/www/ilya/data/www/shop.ivelini.ru

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm i && npm run build

    - name: SSH remote delete dir
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SSH_HOST }}
        port: ${{ env.SSH_PORT }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        script: |
          cd /
          rm -rf ${{ env.WORKDIR }}

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.SSH_HOST }}
        port: ${{ env.SSH_PORT }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        source: ./*, !.gitignore, !.github, !.git, !.gitattributes, !./docker, !./docker-compose.yml, !./node_modules !./vendor
        target: ${{ env.WORKDIR }}

    - name: SSH run remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SSH_HOST }}
        port: ${{ env.SSH_PORT }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        script: |
          cd ${{ env.WORKDIR }}
          cp /var/www/ilya/data/www/build/.env.backend ./.env
          cp /var/www/ilya/data/www/build/composer.phar ./composer.phar
          /opt/php82/bin/php ./composer.phar install
          /opt/php82/bin/php artisan storage:link
          /opt/php82/bin/php artisan migrate --force
          /opt/php82/bin/php ./composer.phar dump-autoload
          /opt/php82/bin/php artisan optimize
          npm i
          npm run build
          chown -R ilya:ilya ${{ env.WORKDIR }}
