name: Laravel

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/scp-action@master
    - name: LS
      run: ls -la
        
      
